import { NextRequest, NextResponse } from "next/server";
import { Project } from "@/types/project";
import { prisma } from "@/lib/prisma";
import { FileData } from "@/types/ai";
import { getUser, getAuthUserId, verifyProjectOwnership } from "@/lib/auth";

export async function POST(request: NextRequest) {
  try {
    const supabaseUser = await getUser();

    if (!supabaseUser) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const userId = supabaseUser.id;

    const projectData: Project = await request.json();
    if (!projectData.id || !projectData.name) {
      return NextResponse.json(
        { error: "Project ID and name are required" },
        { status: 400 }
      );
    }

    // Verify ownership if project already exists in the database
    if (projectData.id) {
      const existingProject = await prisma.projects.findUnique({
        where: { id: projectData.id },
        select: { user_id: true },
      });

      if (existingProject && existingProject.user_id !== userId) {
        return NextResponse.json(
          { error: "Forbidden: You do not own this project" },
          { status: 403 }
        );
      }
    }

    // Start a transaction to ensure data consistency
    const result = await prisma.$transaction(async (tx) => {
      // Ensure user exists in our database to satisfy foreign key constraint.
      // Use real email/name from Supabase so we never create a blank placeholder record.
      await tx.user.upsert({
        where: { id: userId },
        update: {},
        create: {
          id: userId,
          email: supabaseUser.email || '',
          name: supabaseUser.user_metadata?.full_name ||
                supabaseUser.email?.split('@')[0] ||
                'User',
          image: supabaseUser.user_metadata?.avatar_url ||
                 supabaseUser.user_metadata?.picture ||
                 null,
          createdat: new Date(),
          updatedat: new Date(),
        },
      });

      // Upsert the project (update if exists, create if not)
      const project = await tx.projects.upsert({
        where: { id: projectData.id },
        update: {
          name: projectData.name,
          description: projectData.description,
          ...(projectData.prompt !== undefined ? { prompt: projectData.prompt } : {}),
          ...(projectData.github_link !== undefined ? { github_link: projectData.github_link } : {}),
          ...(projectData.vercel_link !== undefined ? { vercel_link: projectData.vercel_link } : {}),
          updated_at: new Date(),
        },
        create: {
          id: projectData.id,
          name: projectData.name,
          description: projectData.description,
          prompt: projectData.prompt ?? null,
          github_link: projectData.github_link ?? null,
          vercel_link: projectData.vercel_link ?? null,
          user_id: userId,
          created_at: new Date(),
          updated_at: new Date(),
        },
      });

      // Delete existing files for this project (to replace them with new ones)
      await tx.project_files.deleteMany({
        where: { project_id: project.id },
      });

      // Create new file records if files are provided
      if (projectData.files && projectData.files.length > 0) {
        await tx.project_files.createMany({
          data: projectData.files.map((file: FileData) => ({
            project_id: project.id,
            path: file.name,
            content: file.content,
            language: file.language,
            editable: true,
            // id and timestamps are generated by the database
          })),
        });
      }

      // If there's a code field (potentially representing main file),
      // we could store it as a special file or handle it differently
      // For now, we'll rely on the files array which should contain the main file

      return project;
    });

    // Fetch the project with its files to return
    const projectWithFiles = await prisma.projects.findUnique({
      where: { id: result.id },
      include: {
        project_files: true,
      },
    });

    // Handle case where project is not found (shouldn't happen in upsert, but safe to check)
    if (!projectWithFiles) {
      throw new Error("Project not found after upsert");
    }

    // Transform to match the Project type expected by the frontend
    const responseProject: Project = {
      id: projectWithFiles.id,
      name: projectWithFiles.name,
      description: projectWithFiles.description ?? undefined,
      prompt: projectWithFiles.prompt ?? undefined,
      code: "",
      files: (projectWithFiles as any).project_files.map((file: any) => ({
        name: file.path,
        content: file.content,
        language: file.language ?? undefined,
      })),
      createdAt: projectWithFiles.created_at,
      updatedAt: projectWithFiles.updated_at,
      userId: projectWithFiles.user_id,
      isPublic: false,
      github_link: projectWithFiles.github_link ?? undefined,
      vercel_link: projectWithFiles.vercel_link ?? undefined,
    };

    return NextResponse.json(responseProject);
  } catch (error) {
    console.error("Error saving project:", error);
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message.includes('Forbidden')) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal error" },
      { status: 500 }
    );
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { id, github_link, vercel_link } = body;

    if (!id) {
      return NextResponse.json(
        { error: "Project ID is required" },
        { status: 400 }
      );
    }

    const existing = await prisma.projects.findUnique({
      where: { id },
      select: { user_id: true },
    });

    if (!existing) {
      return NextResponse.json(
        { error: "Project not found" },
        { status: 404 }
      );
    }

    if (existing.user_id !== userId) {
      return NextResponse.json(
        { error: "Forbidden: You do not own this project" },
        { status: 403 }
      );
    }

    const updated = await prisma.projects.update({
      where: { id },
      data: {
        ...(github_link !== undefined ? { github_link } : {}),
        ...(vercel_link !== undefined ? { vercel_link } : {}),
        updated_at: new Date(),
      },
    });

    return NextResponse.json({
      id: updated.id,
      github_link: updated.github_link ?? undefined,
      vercel_link: updated.vercel_link ?? undefined,
    });
  } catch (error) {
    console.error("Error updating project links:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal error" },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const projectId = request.nextUrl.searchParams.get("id");

    if (projectId) {
      const project = await prisma.projects.findUnique({
        where: { id: projectId },
        include: {
          project_files: true,
        },
      });

      if (!project) {
        return NextResponse.json(
          { error: "Project not found" },
          { status: 404 }
        );
      }

      if (project.user_id !== userId) {
        return NextResponse.json(
          { error: "Forbidden: You do not own this project" },
          { status: 403 }
        );
      }

      // Transform to match the Project type expected by the frontend
      const projectResponse: Project = {
        id: project.id,
        name: project.name,
        description: project.description ?? undefined,
        prompt: project.prompt ?? undefined,
        code: "",
        files: (project as any).project_files.map((file: any) => ({
          name: file.path,
          content: file.content,
          language: file.language ?? undefined,
        })),
        createdAt: project.created_at,
        updatedAt: project.updated_at,
        userId: project.user_id,
        github_link: project.github_link ?? undefined,
        vercel_link: project.vercel_link ?? undefined,
      };

      return NextResponse.json(projectResponse);
    }

    // Get all projects for the authenticated user only
    const projects = await prisma.projects.findMany({
      where: { user_id: userId },
      include: {
        project_files: true,
      },
      orderBy: { updated_at: 'desc' },
    });

    // Transform to match the Project type expected by the frontend
    const projectsResponse: Project[] = projects.map((project) => ({
      id: project.id,
      name: project.name,
      description: project.description ?? undefined,
      prompt: project.prompt ?? undefined,
      code: "",
      files: (project as any).project_files.map((file: any) => ({
        name: file.path,
        content: file.content,
        language: file.language ?? undefined,
      })),
      createdAt: project.created_at,
      updatedAt: project.updated_at,
      userId: project.user_id,
      isPublic: false,
      github_link: project.github_link ?? undefined,
      vercel_link: project.vercel_link ?? undefined,
    }));

    return NextResponse.json(projectsResponse);
  } catch (error) {
    console.error("Error fetching projects:", error);
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message.includes('Forbidden')) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal error" },
      { status: 500 }
    );
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const projectId = request.nextUrl.searchParams.get("id");

    if (!projectId) {
      return NextResponse.json(
        { error: "Project ID is required" },
        { status: 400 }
      );
    }

    // Verify project exists and check ownership before deleting
    const project = await prisma.projects.findUnique({
      where: { id: projectId },
      select: { user_id: true },
    });

    if (!project) {
      return NextResponse.json(
        { error: "Project not found" },
        { status: 404 }
      );
    }

    if (project.user_id !== userId) {
      return NextResponse.json(
        { error: "Forbidden: You do not own this project" },
        { status: 403 }
      );
    }

    await prisma.projects.delete({
      where: { id: projectId },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Error deleting project:", error);
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message.includes('Forbidden')) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    if (error instanceof Error && error.message === 'Project not found') {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal error" },
      { status: 500 }
    );
  }
}