import { NextRequest, NextResponse } from "next/server";
import { Project } from "@/types/project";
import { prisma } from "@/lib/prisma";
import { FileData } from "@/types/ai";
import { getAuthUserId, verifyProjectOwnership } from "@/lib/auth";

export async function POST(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const projectData: Project = await request.json();
    console.log("Received project data:", projectData);
    if (!projectData.id || !projectData.name) {
      return NextResponse.json(
        { error: "Project ID and name are required" },
        { status: 400 }
      );
    }

    // Verify ownership if project ID exists (update case)
    if (projectData.id) {
      await verifyProjectOwnership(projectData.id, userId);
    }

    // Start a transaction to ensure data consistency
    const result = await prisma.$transaction(async (tx) => {
      // Upsert the project (update if exists, create if not)
      const project = await tx.projects.upsert({
        where: { id: projectData.id },
        update: {
          name: projectData.name,
          description: projectData.description,
          thumbnail: projectData.thumbnail,
          updated_at: new Date(),
        },
        create: {
          id: projectData.id,
          name: projectData.name,
          description: projectData.description,
          thumbnail: projectData.thumbnail,
          user_id: userId,
          created_at: new Date(),
          updated_at: new Date(),
        },
      });

      // Delete existing files for this project (to replace them with new ones)
      await tx.project_files.deleteMany({
        where: { project_id: project.id },
      });

      // Create new file records if files are provided
      if (projectData.files && projectData.files.length > 0) {
        await tx.project_files.createMany({
          data: projectData.files.map((file: FileData) => ({
            project_id: project.id,
            path: file.name,
            content: file.content,
            language: file.language,
            editable: true,
            // id and timestamps are generated by the database
          })),
        });
      }

      // If there's a code field (potentially representing main file),
      // we could store it as a special file or handle it differently
      // For now, we'll rely on the files array which should contain the main file

      return project;
    });

    // Fetch the project with its files to return
    const projectWithFiles = await prisma.projects.findUnique({
      where: { id: result.id },
      include: {
        project_files: true,
      },
    });

    // Handle case where project is not found (shouldn't happen in upsert, but safe to check)
    if (!projectWithFiles) {
      throw new Error("Project not found after upsert");
    }

    // Transform to match the Project type expected by the frontend
    const responseProject: Project = {
      id: projectWithFiles.id,
      name: projectWithFiles.name,
      description: projectWithFiles.description ?? undefined,
      code: "",
      files: (projectWithFiles as any).project_files.map((file: any) => ({
        name: file.path,
        content: file.content,
        language: file.language ?? undefined,
      })),
      createdAt: projectWithFiles.created_at,
      updatedAt: projectWithFiles.updated_at,
      userId: projectWithFiles.user_id,
      thumbnail: projectWithFiles.thumbnail ?? undefined,
      isPublic: false,
    };

    return NextResponse.json(responseProject);
  } catch (error) {
    console.error("Error saving project:", error);
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message.includes('Forbidden')) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal error" },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const projectId = request.nextUrl.searchParams.get("id");

    if (projectId) {
      // Verify ownership of the specific project
      await verifyProjectOwnership(projectId, userId);

      const project = await prisma.projects.findUnique({
        where: { id: projectId },
        include: {
          project_files: true,
        },
      });

      if (!project) {
        return NextResponse.json(
          { error: "Project not found" },
          { status: 404 }
        );
      }

      // Transform to match the Project type expected by the frontend
      const projectResponse: Project = {
        id: project.id,
        name: project.name,
        description: project.description ?? undefined,
        code: "",
        files: (project as any).project_files.map((file: any) => ({
          name: file.path,
          content: file.content,
          language: file.language ?? undefined,
        })),
        createdAt: project.created_at,
        updatedAt: project.updated_at,
        userId: project.user_id,
        thumbnail: project.thumbnail ?? undefined,
      };

      return NextResponse.json(projectResponse);
    }

    // Get all projects for the authenticated user only
    const projects = await prisma.projects.findMany({
      where: { user_id: userId },
      include: {
        project_files: true,
      },
      orderBy: { updated_at: 'desc' },
    });

    // Transform to match the Project type expected by the frontend
    const projectsResponse: Project[] = projects.map((project) => ({
      id: project.id,
      name: project.name,
      description: project.description ?? undefined,
      code: "",
      files: (project as any).project_files.map((file: any) => ({
        name: file.path,
        content: file.content,
        language: file.language ?? undefined,
      })),
      createdAt: project.created_at,
      updatedAt: project.updated_at,
      userId: project.user_id,
      thumbnail: project.thumbnail ?? undefined,
      isPublic: false,
    }));

    return NextResponse.json(projectsResponse);
  } catch (error) {
    console.error("Error fetching projects:", error);
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message.includes('Forbidden')) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal error" },
      { status: 500 }
    );
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const projectId = request.nextUrl.searchParams.get("id");

    if (!projectId) {
      return NextResponse.json(
        { error: "Project ID is required" },
        { status: 400 }
      );
    }

    // Verify ownership before deleting
    await verifyProjectOwnership(projectId, userId);

    await prisma.projects.delete({
      where: { id: projectId },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Error deleting project:", error);
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message.includes('Forbidden')) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    if (error instanceof Error && error.message === 'Project not found') {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal error" },
      { status: 500 }
    );
  }
}