import JSZip from "jszip";
import { saveAs } from "file-saver";
import { FileData } from "@/types/ai";

export async function createProjectZip(
  projectName: string,
  files: FileData[],
  code: string
): Promise<Blob> {
  const zip = new JSZip();

  // Add main code file
  zip.file(
    "src/App.jsx",
    code || "export default function App() { return <div>App</div>; }"
  );

  // Add additional files
  files.forEach((file) => {
    const filePath = file.name.startsWith("/") ? file.name.slice(1) : file.name;
    zip.file(`src/${filePath}`, file.content);
  });

  // Add package.json
  zip.file(
    "package.json",
    JSON.stringify(
      {
        name: projectName || "ai-website",
        version: "0.1.0",
        private: true,
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          "react-scripts": "5.0.1",
        },
        scripts: {
          start: "react-scripts start",
          build: "react-scripts build",
          test: "react-scripts test",
          eject: "react-scripts eject",
        },
        eslintConfig: {
          extends: ["react-app"],
        },
        browserslist: {
          production: [">0.2%", "not dead", "not op_mini all"],
          development: [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version",
          ],
        },
      },
      null,
      2
    )
  );

  // Add README
  zip.file(
    "README.md",
    `# ${projectName || "AI Website"}

Generated by AI Website Builder

## Getting Started

\`\`\`bash
npm install
npm start
\`\`\`
`
  );

  // Add public/index.html
  zip.file(
    "public/index.html",
    `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <title>${projectName || "AI Website"}</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>`
  );

  return await zip.generateAsync({ type: "blob" });
}

export async function downloadProjectZip(
  projectName: string,
  files: FileData[],
  code: string
): Promise<void> {
  const blob = await createProjectZip(projectName, files, code);
  saveAs(blob, `${projectName || "project"}.zip`);
}

// Note: You'll need to install dependencies:
// npm install jszip file-saver
// npm install --save-dev @types/file-saver
