import JSZip from "jszip";
import { saveAs } from "file-saver";
import { FileData } from "@/types/ai";

export async function createProjectZip(
  projectName: string,
  files: FileData[],
  code: string
): Promise<Blob> {
  const zip = new JSZip();

  // Add main code file
  zip.file(
    "src/App.jsx",
    code || "export default function App() { return <div>App</div>; }"
  );

  // Add additional files
  files.forEach((file) => {
    const filePath = file.name.startsWith("/") ? file.name.slice(1) : file.name;
    
    // If it's already a root file (config files, index.html), don't prepend src/
    if (
      filePath === "package.json" || 
      filePath.startsWith("public/") || 
      filePath === "index.html" ||
      filePath === "vite.config.js" ||
      filePath === "tailwind.config.js" ||
      filePath === "postcss.config.js"
    ) {
      let content = file.content;
      if (filePath === "index.html") {
        content = content.replace(/<script\s+src=["']https:\/\/cdn\.tailwindcss\.com["']><\/script>\s*/gi, "");
      } else if (filePath === "package.json") {
        try {
          const parsed = JSON.parse(content);
          parsed.devDependencies = {
            "@vitejs/plugin-react": "^4.3.4",
            "vite": "^5.4.14",
            "tailwindcss": "^3.4.17",
            "postcss": "^8.4.49",
            "autoprefixer": "^10.4.20",
            ...(parsed.devDependencies || {}),
          };
          content = JSON.stringify(parsed, null, 2);
        } catch {
          // keep original content if invalid JSON
        }
      }
      zip.file(filePath, content);
    } else {
      const targetPath = filePath.startsWith("src/") ? filePath : `src/${filePath}`;
      let content = file.content;
      if (targetPath === "src/index.css" || targetPath === "src/styles.css") {
        if (!content.includes("@tailwind")) {
          content = `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n${content}`;
        }
      }
      zip.file(targetPath, content);
    }
  });

  // Add package.json only if not already provided
  const hasPackageJson = files.some(f => f.name === "package.json" || f.name === "/package.json");
  if (!hasPackageJson) {
    zip.file(
      "package.json",
      JSON.stringify(
        {
          name: projectName || "ai-website",
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "vite",
            build: "vite build",
            preview: "vite preview",
          },
          dependencies: {
            react: "^18.3.1",
            "react-dom": "^18.3.1",
            "lucide-react": "^0.475.0"
          },
          devDependencies: {
            "@vitejs/plugin-react": "^4.3.4",
            "vite": "^5.4.14",
            "tailwindcss": "^3.4.17",
            "postcss": "^8.4.49",
            "autoprefixer": "^10.4.20"
          },
        },
        null,
        2
      )
    );
  }

  // Add README
  zip.file(
    "README.md",
    `# ${projectName || "AI Website"}

Generated by AI Website Builder

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
`
  );

  // Add index.html only if not already provided (Vite uses index.html at root)
  const hasIndexHtml = files.some(f => f.name === "index.html" || f.name === "/index.html");
  if (!hasIndexHtml) {
    zip.file(
      "index.html",
      `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName || "AI Website"}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`
    );
  }

  const hasViteConfig = files.some(f => f.name === "vite.config.js" || f.name === "/vite.config.js");
  if (!hasViteConfig) {
    zip.file(
      "vite.config.js",
      `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});`
    );
  }

  // Add tailwind.config.js only if not already provided
  const hasTailwindConfig = files.some(f => f.name === "tailwind.config.js" || f.name === "/tailwind.config.js");
  if (!hasTailwindConfig) {
    zip.file(
      "tailwind.config.js",
      `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
    );
  }

  // Add postcss.config.js only if not already provided
  const hasPostcssConfig = files.some(f => f.name === "postcss.config.js" || f.name === "/postcss.config.js");
  if (!hasPostcssConfig) {
    zip.file(
      "postcss.config.js",
      `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
    );
  }


  // Add src/main.jsx only if not already provided
  const hasMainJsx = files.some(f => f.name === "src/main.jsx" || f.name === "/src/main.jsx");
  if (!hasMainJsx) {
    zip.file(
      "src/main.jsx",
      `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`
    );
  }

  const hasIndexCss = files.some(f => f.name === "src/index.css" || f.name === "/src/index.css");
  if (!hasIndexCss) {
    zip.file(
      "src/index.css",
      `@tailwind base;
@tailwind components;
@tailwind utilities;`
    );
  }

  return await zip.generateAsync({ type: "blob" });
}

export async function downloadProjectZip(
  projectName: string,
  files: FileData[],
  code: string
): Promise<void> {
  const blob = await createProjectZip(projectName, files, code);
  saveAs(blob, `${projectName || "project"}.zip`);
}

// Note: You'll need to install dependencies:
// npm install jszip file-saver
// npm install --save-dev @types/file-saver
